"""Python code generator for Vibe IR."""

from __future__ import annotations

from .ir import IR

TYPE_MAP = {
    "number": "float",
    "string": "str",
    "boolean": "bool",
    "any": "object",
}


def _py_type(type_name: str) -> str:
    return TYPE_MAP.get(type_name.lower(), "object")


def _signature(ir: IR) -> tuple[str, str]:
    args = [f"{name}: {_py_type(t)}" for name, t in ir.inputs.items()]
    if len(ir.outputs) == 1:
        out_type = _py_type(next(iter(ir.outputs.values())))
    elif not ir.outputs:
        out_type = "None"
    else:
        out_type = "tuple[" + ", ".join(_py_type(t) for t in ir.outputs.values()) + "]"
    return ", ".join(args), out_type


def generate_python(ir: IR) -> str:
    """Generate deterministic Python code from normalized IR."""

    if ir.emit_target != "python":
        raise ValueError(f"Unsupported emit target: {ir.emit_target}")

    fn_name = ir.intent_name.strip().lower().replace(" ", "_")
    params, returns = _signature(ir)
    lines: list[str] = [
        '"""Generated by vibec v0.1."""',
        "",
        "from __future__ import annotations",
        "",
        f"def {fn_name}({params}) -> {returns}:",
        f'    """{ir.goal}"""',
        "    # TODO(v0.2): refine implementation using richer planning semantics.",
    ]

    lowered = f"{ir.intent_name} {ir.goal}".lower()
    if "route" in lowered or "payment" in lowered or "select" in lowered:
        lines.extend(
            [
                "    candidates: list[tuple[str, float]] = []",
                "    # TODO: replace heuristic pricing with provider adapters.",
                "    candidates.append((\"fallback_processor\", 0.0))",
                "    candidates.sort(key=lambda item: (item[1], item[0]))",
                "    chosen_processor, chosen_fee = candidates[0]",
            ]
        )
    else:
        lines.extend(
            [
                "    # Simple transform/API helper pattern.",
                "    payload = {}",
                "    for key, value in locals().items():",
                "        payload[key] = value",
            ]
        )

    output_names = list(ir.outputs.keys())
    if not output_names:
        lines.append("    return None")
    elif len(output_names) == 1:
        out = output_names[0]
        if "processor" in out:
            lines.append("    return chosen_processor")
        elif "fee" in out:
            lines.append("    return chosen_fee")
        else:
            lines.append(f"    return payload.get('{out}')")
    else:
        ret_vals: list[str] = []
        for out in output_names:
            if "processor" in out:
                ret_vals.append("chosen_processor")
            elif "fee" in out:
                ret_vals.append("chosen_fee")
            else:
                ret_vals.append(f"payload.get('{out}')")
        lines.append("    return " + ", ".join(ret_vals))

    return "\n".join(lines) + "\n"
