from __future__ import annotations

import json
from pathlib import Path


def _slug(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in name).strip("_") or "artifact"


def export_artifact_bundle(export_dir: Path, prefix: str, payload: dict[str, object], title: str) -> dict[str, object]:
    export_dir.mkdir(parents=True, exist_ok=True)
    stem = _slug(prefix)
    json_path = export_dir / f"{stem}.json"
    md_path = export_dir / f"{stem}.md"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(
        f"# {title}\n\n"
        f"Artifact: `{json_path.name}`\n\n"
        "Scope note: local review artifact generated by bounded PhiPython tooling.\n",
        encoding="utf-8",
    )
    return {
        "export_dir": str(export_dir),
        "json": str(json_path),
        "markdown": str(md_path),
        "notes": ["Artifacts are local review outputs, not proofs of correctness."],
    }
