from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PythonTemplate:
    """Project scaffold template entry."""

    name: str
    description: str
    files: dict[str, str]


def _base_readme(template_name: str, project_name: str, description: str) -> str:
    return (
        f"# {project_name}\n\n"
        f"Generated by PhiPython template `{template_name}`.\n\n"
        f"{description}\n\n"
        "## Quickstart\n\n"
        "```bash\n"
        "python -m pip install -r requirements.txt\n"
        "python main.py\n"
        "```\n\n"
        "Scope note: this is a bounded starter kit intended for local learning and iteration.\n"
    )


_TEMPLATE_REGISTRY: dict[str, PythonTemplate] = {
    "api_tool": PythonTemplate(
        name="api_tool",
        description="Requests-based API starter with JSON output helper.",
        files={
            "main.py": (
                '"""PhiPython API starter: deterministic, inspectable, and intentionally small."""\n\n'
                "import argparse\n"
                "import json\n"
                "import requests\n\n"
                "def fetch_json(url: str) -> dict:\n"
                "    response = requests.get(url, timeout=10)\n"
                "    response.raise_for_status()\n"
                "    return response.json()\n\n"
                "def main() -> int:\n"
                "    parser = argparse.ArgumentParser(description=\"API tool starter\")\n"
                "    parser.add_argument(\"--url\", default=\"https://api.github.com\")\n"
                "    args = parser.parse_args()\n"
                "    payload = fetch_json(args.url)\n"
                "    print(json.dumps(payload, indent=2))\n"
                "    return 0\n\n"
                "if __name__ == \"__main__\":\n"
                "    raise SystemExit(main())\n"
            ),
            "requirements.txt": "requests>=2.31.0\n",
            "tests/test_main.py": (
                "from main import fetch_json\n\n"
                "def test_fetch_json_is_callable() -> None:\n"
                "    assert callable(fetch_json)\n"
            ),
        },
    ),
    "automation": PythonTemplate(
        name="automation",
        description="Filesystem automation starter with clear extension points.",
        files={
            "main.py": (
                '"""PhiPython automation starter. TODO: tailor file-matching for your workflow."""\n\n'
                "from pathlib import Path\n\n"
                "def run(root: Path) -> list[str]:\n"
                "    names: list[str] = []\n"
                "    for entry in sorted(root.glob('*.txt')):\n"
                "        names.append(entry.name)\n"
                "        print(f\"found: {entry.name}\")\n"
                "    return names\n\n"
                "if __name__ == \"__main__\":\n"
                "    run(Path('.'))\n"
            ),
            "requirements.txt": "",
            "examples/input.txt": "example file\n",
        },
    ),
    "cli": PythonTemplate(
        name="cli",
        description="argparse-based CLI starter with tiny test and usage examples.",
        files={
            "main.py": (
                '"""PhiPython CLI starter with deterministic argparse setup."""\n\n'
                "import argparse\n\n"
                "def build_parser() -> argparse.ArgumentParser:\n"
                "    parser = argparse.ArgumentParser(description=\"PhiPython CLI starter\")\n"
                "    parser.add_argument('name', help=\"Name to greet\")\n"
                "    parser.add_argument('--caps', action='store_true', help='Uppercase output')\n"
                "    return parser\n\n"
                "def main() -> int:\n"
                "    args = build_parser().parse_args()\n"
                "    message = f\"hello {args.name}\"\n"
                "    print(message.upper() if args.caps else message)\n"
                "    return 0\n\n"
                "if __name__ == \"__main__\":\n"
                "    raise SystemExit(main())\n"
            ),
            "requirements.txt": "",
            "tests/test_parser.py": (
                "from main import build_parser\n\n"
                "def test_parser_accepts_name() -> None:\n"
                "    args = build_parser().parse_args([\"alice\"])\n"
                "    assert args.name == \"alice\"\n"
            ),
        },
    ),
    "dashboard": PythonTemplate(
        name="dashboard",
        description="Streamlit dashboard starter with CSV upload flow.",
        files={
            "main.py": (
                "import streamlit as st\n"
                "import pandas as pd\n\n"
                "st.title(\"PhiPython Dashboard\")\n"
                "file = st.file_uploader(\"Upload CSV\", type=[\"csv\"])\n"
                "if file is not None:\n"
                "    frame = pd.read_csv(file)\n"
                "    st.dataframe(frame.head())\n"
                "    st.caption(\"TODO: add domain-specific visualizations\")\n"
            ),
            "requirements.txt": "streamlit>=1.35.0\npandas>=2.0.0\n",
            "examples/sample.csv": "name,value\nalpha,1\nbeta,2\n",
        },
    ),
    "flask_app": PythonTemplate(
        name="flask_app",
        description="Flask starter with app factory and health route.",
        files={
            "main.py": (
                "from app import create_app\n\n"
                "app = create_app()\n\n"
                "if __name__ == \"__main__\":\n"
                "    app.run(debug=True)\n"
            ),
            "app.py": (
                "from flask import Flask, jsonify\n\n"
                "def create_app() -> Flask:\n"
                "    app = Flask(__name__)\n\n"
                "    @app.get('/health')\n"
                "    def health() -> tuple[dict[str, str], int]:\n"
                "        return jsonify({\"status\": \"ok\"}), 200\n\n"
                "    return app\n"
            ),
            "requirements.txt": "flask>=3.0.0\n",
            ".env.example": "FLASK_DEBUG=1\n",
            "tests/test_app.py": (
                "from app import create_app\n\n"
                "def test_health_route_exists() -> None:\n"
                "    app = create_app()\n"
                "    assert app is not None\n"
            ),
        },
    ),
    "scraper": PythonTemplate(
        name="scraper",
        description="HTML scraper starter with URL argument and error surfacing.",
        files={
            "main.py": (
                "import argparse\n"
                "import requests\n"
                "from bs4 import BeautifulSoup\n\n"
                "def scrape_title(url: str) -> str:\n"
                "    response = requests.get(url, timeout=10)\n"
                "    response.raise_for_status()\n"
                "    soup = BeautifulSoup(response.text, 'html.parser')\n"
                "    return (soup.title.string or '').strip()\n\n"
                "def main() -> int:\n"
                "    parser = argparse.ArgumentParser(description=\"HTML title scraper starter\")\n"
                "    parser.add_argument('--url', default='https://example.com')\n"
                "    args = parser.parse_args()\n"
                "    print(scrape_title(args.url))\n"
                "    return 0\n\n"
                "if __name__ == \"__main__\":\n"
                "    raise SystemExit(main())\n"
            ),
            "requirements.txt": "requests>=2.31.0\nbeautifulsoup4>=4.12.0\n",
            "examples/targets.txt": "https://example.com\n",
        },
    ),
}


def list_templates() -> list[PythonTemplate]:
    return [_TEMPLATE_REGISTRY[key] for key in sorted(_TEMPLATE_REGISTRY)]


def get_template(name: str) -> PythonTemplate | None:
    return _TEMPLATE_REGISTRY.get(name)


def template_as_dict(name: str) -> dict[str, object]:
    template = get_template(name)
    if template is None:
        raise KeyError(f"unknown template: {name}")
    return {
        "name": template.name,
        "description": template.description,
        "files": dict(sorted(template.files.items())),
    }


def render_template_files(template_name: str, project_name: str) -> dict[str, str]:
    template = get_template(template_name)
    if template is None:
        raise KeyError(f"unknown template: {template_name}")
    files = dict(template.files)
    files["README.md"] = _base_readme(template_name, project_name, template.description)
    return files
