from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PythonTemplate:
    """Project scaffold template entry."""

    name: str
    description: str
    files: dict[str, str]


def _base_readme(template_name: str, project_name: str) -> str:
    return (
        f"# {project_name}\n\n"
        f"Generated by PhiPython template `{template_name}`.\n\n"
        "Scope note: this is a starter scaffold. Review and extend for production use.\n"
    )


_TEMPLATE_REGISTRY: dict[str, PythonTemplate] = {
    "api_tool": PythonTemplate(
        name="api_tool",
        description="Command-line API caller scaffold.",
        files={
            "main.py": (
                "import json\n\n"
                "import requests\n\n"
                "def fetch_json(url: str) -> dict:\n"
                "    response = requests.get(url, timeout=10)\n"
                "    response.raise_for_status()\n"
                "    return response.json()\n\n"
                "if __name__ == \"__main__\":\n"
                "    payload = fetch_json(\"https://api.github.com\")\n"
                "    print(json.dumps(payload, indent=2))\n"
            ),
            "requirements.txt": "requests>=2.31.0\n",
        },
    ),
    "automation": PythonTemplate(
        name="automation",
        description="Simple file-system automation script.",
        files={
            "main.py": (
                "from pathlib import Path\n\n"
                "def run() -> None:\n"
                "    root = Path('.')\n"
                "    for entry in sorted(root.glob('*.txt')):\n"
                "        print(f\"found: {entry.name}\")\n\n"
                "if __name__ == \"__main__\":\n"
                "    run()\n"
            ),
            "requirements.txt": "",
        },
    ),
    "cli": PythonTemplate(
        name="cli",
        description="argparse-based command line starter.",
        files={
            "main.py": (
                "import argparse\n\n"
                "def build_parser() -> argparse.ArgumentParser:\n"
                "    parser = argparse.ArgumentParser(description=\"PhiPython CLI starter\")\n"
                "    parser.add_argument('name', help=\"Name to greet\")\n"
                "    return parser\n\n"
                "def main() -> int:\n"
                "    args = build_parser().parse_args()\n"
                "    print(f\"hello {args.name}\")\n"
                "    return 0\n\n"
                "if __name__ == \"__main__\":\n"
                "    raise SystemExit(main())\n"
            ),
            "requirements.txt": "",
        },
    ),
    "dashboard": PythonTemplate(
        name="dashboard",
        description="Minimal Streamlit dashboard starter.",
        files={
            "main.py": (
                "import streamlit as st\n\n"
                "st.title(\"PhiPython Dashboard\")\n"
                "st.write(\"Edit this app to visualize your project metrics.\")\n"
            ),
            "requirements.txt": "streamlit>=1.35.0\n",
        },
    ),
    "flask_app": PythonTemplate(
        name="flask_app",
        description="Minimal Flask web app scaffold.",
        files={
            "main.py": (
                "from flask import Flask, jsonify\n\n"
                "app = Flask(__name__)\n\n"
                "@app.get('/health')\n"
                "def health() -> tuple[dict[str, str], int]:\n"
                "    return jsonify({\"status\": \"ok\"}), 200\n\n"
                "if __name__ == \"__main__\":\n"
                "    app.run(debug=True)\n"
            ),
            "requirements.txt": "flask>=3.0.0\n",
        },
    ),
    "scraper": PythonTemplate(
        name="scraper",
        description="HTML scraping starter with BeautifulSoup.",
        files={
            "main.py": (
                "import requests\n"
                "from bs4 import BeautifulSoup\n\n"
                "def scrape_title(url: str) -> str:\n"
                "    response = requests.get(url, timeout=10)\n"
                "    response.raise_for_status()\n"
                "    soup = BeautifulSoup(response.text, 'html.parser')\n"
                "    return (soup.title.string or '').strip()\n\n"
                "if __name__ == \"__main__\":\n"
                "    print(scrape_title('https://example.com'))\n"
            ),
            "requirements.txt": "requests>=2.31.0\nbeautifulsoup4>=4.12.0\n",
        },
    ),
}


def list_templates() -> list[PythonTemplate]:
    """Return templates in deterministic name order."""

    return [_TEMPLATE_REGISTRY[key] for key in sorted(_TEMPLATE_REGISTRY)]


def get_template(name: str) -> PythonTemplate | None:
    """Lookup a template by exact name."""

    return _TEMPLATE_REGISTRY.get(name)


def render_template_files(template_name: str, project_name: str) -> dict[str, str]:
    """Render the file map for a template with stable README inclusion."""

    template = get_template(template_name)
    if template is None:
        raise KeyError(f"unknown template: {template_name}")
    files = dict(template.files)
    files["README.md"] = _base_readme(template_name, project_name)
    return files
