from __future__ import annotations

import json
from pathlib import Path

from .scaffold_metadata import read_metadata
from .test_profiles import TEST_MANIFEST_FILE, TEST_PROFILE_VERSION, get_test_profile


def _guess_template_for_testgen(path: Path, metadata: dict[str, object] | None) -> str:
    if metadata and isinstance(metadata.get("template"), str):
        return str(metadata["template"])
    files = {p.name for p in path.glob("*")}
    if "app.py" in files and ".env.example" in files:
        return "flask_app"
    if "examples" in files and (path / "examples" / "sample.csv").exists():
        return "dashboard"
    if "requirements.txt" in files and "requests" in (path / "requirements.txt").read_text(encoding="utf-8"):
        return "api_tool"
    if "tests" in files and (path / "tests" / "test_parser.py").exists():
        return "cli"
    return "unknown"


def _render_test_file(template: str) -> str:
    header = "# Generated by PhiPython v1.4\n# Starter-oriented tests only; not proof of correctness.\n"
    common = "import importlib\n\n\ndef test_main_import_smoke():\n    importlib.import_module('main')\n"
    if template == "flask_app":
        return (
            header
            + "import importlib\n\n"
            + "def test_app_object_exists():\n"
            + "    app_mod = importlib.import_module('app')\n"
            + "    assert hasattr(app_mod, 'app')\n\n"
            + "def test_root_route_smoke():\n"
            + "    app_mod = importlib.import_module('app')\n"
            + "    app = getattr(app_mod, 'app')\n"
            + "    client = app.test_client()\n"
            + "    res = client.get('/')\n"
            + "    assert res.status_code < 500\n"
        )
    if template == "scraper":
        return header + common + "\n\ndef test_inline_html_hint():\n    html = '<html><body><h1>x</h1></body></html>'\n    assert '<h1>' in html\n"
    if template == "api_tool":
        return header + common + "\n\ndef test_no_network_policy_note():\n    assert True  # network calls are intentionally out-of-scope\n"
    if template == "dashboard":
        return header + common + "\n\ndef test_helper_smoke_placeholder():\n    assert True\n"
    if template == "automation":
        return header + common + "\n\ndef test_automation_smoke_placeholder():\n    assert True\n"
    return header + common + "\n\ndef test_cli_smoke_placeholder():\n    assert True\n"


def generate_tests(project_path: Path, template: str | None = None, apply: bool = False) -> dict[str, object]:
    metadata = read_metadata(project_path)
    guessed = template or _guess_template_for_testgen(project_path, metadata)
    profile = get_test_profile(guessed)
    if profile is None:
        return {
            "can_generate": False,
            "project": str(project_path),
            "template": guessed,
            "reason": "No bounded test profile for inferred template.",
            "generated": [],
        }

    files: list[dict[str, object]] = []
    for rel in profile.test_files:
        target = project_path / rel
        before = target.read_text(encoding="utf-8") if target.exists() else ""
        after = _render_test_file(profile.template)
        files.append({"path": str(target), "preview": {"before": before, "after": after}})

    manifest = {
        "manifest_type": "phipython_test_generation",
        "generation_version": TEST_PROFILE_VERSION,
        "template": profile.template,
        "generated_tests": [f["path"] for f in files],
        "covered_signals": list(profile.covered_signals),
        "skipped_areas": list(profile.skipped_areas),
        "notes": list(profile.notes),
    }

    applied = False
    if apply:
        for entry in files:
            out = Path(str(entry["path"]))
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(str(entry["preview"]["after"]), encoding="utf-8")
        (project_path / TEST_MANIFEST_FILE).write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        applied = True

    return {
        "can_generate": True,
        "project": str(project_path),
        "template": profile.template,
        "applied": applied,
        "files": files,
        "manifest": manifest,
        "notes": ["Generated tests are starter-aware smoke tests, not exhaustive correctness checks."],
    }


def read_test_manifest(project_path: Path) -> dict[str, object] | None:
    manifest_path = project_path / TEST_MANIFEST_FILE
    if not manifest_path.exists():
        return None
    return json.loads(manifest_path.read_text(encoding="utf-8"))
