"""Python code generator for Vibe IR."""

from __future__ import annotations

import re

from .ir import IR

TYPE_MAP = {
    "number": "float",
    "string": "str",
    "boolean": "bool",
    "any": "object",
}


def _py_type(type_name: str) -> str:
    return TYPE_MAP.get(type_name.lower(), "object")


def _snake_name(name: str) -> str:
    collapsed = re.sub(r"[^0-9a-zA-Z]+", "_", name).strip("_")
    return re.sub(r"(?<!^)(?=[A-Z])", "_", collapsed).lower() or "generated_intent"


def _signature(ir: IR) -> tuple[str, str]:
    args = [f"{name}: {_py_type(t)}" for name, t in ir.inputs.items()]
    if len(ir.outputs) == 1:
        out_type = _py_type(next(iter(ir.outputs.values())))
    elif not ir.outputs:
        out_type = "None"
    else:
        out_type = "tuple[" + ", ".join(_py_type(t) for t in ir.outputs.values()) + "]"
    return ", ".join(args), out_type


def generate_python(ir: IR) -> str:
    """Generate deterministic Python code from normalized IR."""

    if ir.emit_target != "python":
        raise ValueError(f"Unsupported emit target: {ir.emit_target}")

    fn_name = _snake_name(ir.intent_name)
    params, returns = _signature(ir)
    lines: list[str] = [
        '"""Generated by vibec v0.1."""',
        "",
        "from __future__ import annotations",
        "",
        f"# SEMANTIC_QUALIFIERS: {ir.module.semantic_summary.get('binding_qualifiers', {})}",
        f"# EFFECT_PROFILE: {ir.module.effect_summary}",
        f"# RESOURCE_PROFILE: {ir.module.resource_summary}",
        f"# INFERENCE_PROFILE: {ir.module.inference_summary}",
        f"# AGENT_GRAPH: {ir.module.agent_graph_summary}",
        f"# AGENT_BOUNDARY_BRIDGES: {ir.module.agent_boundary_summary}",
        f"# AGENT_DELEGATION: {ir.module.delegation_summary}",
        f"# RUNTIME_MONITOR: {ir.module.runtime_monitor}",
        f"AGENT_GRAPH_CONFIG = {ir.module.agent_graph}",
        f"AGENT_BOUNDARY_BRIDGES = {ir.module.agent_boundary_summary}",
        f"AGENT_DELEGATION = {ir.module.delegation_summary}",
        f"MONITOR_CONFIG = {ir.module.runtime_monitor}",
        "",
        "def monitor_event_hook(event: dict[str, object]) -> None:",
        '    """Runtime monitor hook stub (Phase 5.4; observational only)."""',
        "    _ = event",
        "",
        f"def {fn_name}({params}) -> {returns}:",
        f'    """{ir.goal}"""',
        "    # TODO(v0.2): refine implementation using richer planning semantics.",
    ]

    lowered = f"{ir.intent_name} {ir.goal}".lower()
    if "route" in lowered or "payment" in lowered or "select" in lowered:
        lines.extend(
            [
                "    candidates: list[tuple[str, float]] = []",
                "    # TODO: replace heuristic pricing with provider adapters.",
                "    candidates.append((\"fallback_processor\", 0.0))",
                "    candidates.sort(key=lambda item: (item[1], item[0]))",
                "    chosen_processor, chosen_fee = candidates[0]",
            ]
        )
    else:
        lines.extend(
            [
                "    # Simple transform/API helper pattern.",
                "    payload: dict[str, object] = {}",
                "    for key in sorted(locals()):",
                "        payload[key] = locals()[key]",
            ]
        )

    output_names = list(ir.outputs.keys())
    if not output_names:
        lines.append("    return None")
    elif len(output_names) == 1:
        out = output_names[0]
        if "processor" in out:
            lines.append("    return chosen_processor")
        elif "fee" in out:
            lines.append("    return chosen_fee")
        else:
            lines.append(f"    return payload.get('{out}')")
    else:
        ret_vals: list[str] = []
        for out in output_names:
            if "processor" in out:
                ret_vals.append("chosen_processor")
            elif "fee" in out:
                ret_vals.append("chosen_fee")
            else:
                ret_vals.append(f"payload.get('{out}')")
        lines.append("    return " + ", ".join(ret_vals))


    lines.append("")
    lines.append("# Experimental research/operational stubs (non-hardware, non-biological control).")
    if ir.tesla_victory_layer:
        lines.append(f"TESLA_VICTORY_LAYER = {ir.arc_tower_policy | ir.life_ray_protocol | ir.breath_cycle_protocol!r}")
    if ir.agentora_config.get("enabled"):
        lines.append(f"AGENTORA_CONFIG = {ir.agentora_config!r}")
        lines.append(f"AGENT_DEFINITIONS = {ir.agent_definitions!r}")
    if ir.agentception_config:
        lines.append(f"AGENTCEPTION_CONFIG = {ir.agentception_config!r}")

    return "\n".join(lines) + "\n"
