"""TypeScript code generator for typed SSA IR."""

from __future__ import annotations

import re

from .ir import IR

TS_TYPE_MAP = {
    "number": "number",
    "string": "string",
    "boolean": "boolean",
    "any": "unknown",
}


def _ts_type(type_name: str) -> str:
    return TS_TYPE_MAP.get(type_name.lower(), "unknown")


def _camel_name(name: str) -> str:
    safe = re.sub(r"[^0-9a-zA-Z]+", " ", name).strip()
    if not safe:
        return "generatedIntent"
    parts = safe.split()
    first = parts[0].lower()
    rest = "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return first + rest


def _signature(ir: IR) -> tuple[str, str]:
    params = [f"{name}: {_ts_type(t)}" for name, t in ir.inputs.items()]
    if len(ir.outputs) == 1:
        ret = _ts_type(next(iter(ir.outputs.values())))
    elif not ir.outputs:
        ret = "void"
    else:
        fields = "; ".join(f"{name}: {_ts_type(tp)}" for name, tp in ir.outputs.items())
        ret = f"{{ {fields} }}"
    return ", ".join(params), ret


def generate_typescript(ir: IR) -> str:
    """Generate deterministic TypeScript from typed SSA IR."""

    fn_name = _camel_name(ir.intent_name)
    params, ret = _signature(ir)
    lines: list[str] = [
        "// Generated by vibec v0.2",
        "",
        f"/** {ir.goal} */",
        f"export function {fn_name}({params}): {ret} {{",
        "  // TODO(v0.3): enrich planning semantics for deeper intent realization.",
    ]

    lowered = f"{ir.intent_name} {ir.goal}".lower()
    if "route" in lowered or "payment" in lowered or "select" in lowered:
        lines.extend(
            [
                "  const candidates: Array<[string, number]> = [];",
                "  // Preserve constraints using deterministic ranking.",
                "  candidates.push(['fallback_processor', 0]);",
                "  candidates.sort((a, b) => (a[1] - b[1]) || a[0].localeCompare(b[0]));",
                "  const [chosenProcessor, chosenFee] = candidates[0];",
            ]
        )
    else:
        lines.extend(
            [
                "  // Transform/helper pattern (no runtime autonomy).",
                "  const payload: Record<string, unknown> = {};",
                "  Object.keys({" + ", ".join(ir.inputs.keys()) + "}).sort().forEach((k) => {",
                "    payload[k] = ( {" + ", ".join(ir.inputs.keys()) + "} as Record<string, unknown> )[k];",
                "  });",
            ]
        )

    out_names = list(ir.outputs.keys())
    if not out_names:
        lines.append("  return;")
    elif len(out_names) == 1:
        name = out_names[0]
        if "processor" in name:
            lines.append("  return chosenProcessor as any;")
        elif "fee" in name:
            lines.append("  return chosenFee as any;")
        else:
            lines.append(f"  return payload['{name}'] as any;")
    else:
        obj_parts: list[str] = []
        for n in out_names:
            if "processor" in n:
                obj_parts.append(f"{n}: chosenProcessor")
            elif "fee" in n:
                obj_parts.append(f"{n}: chosenFee")
            else:
                obj_parts.append(f"{n}: payload['{n}']")
        lines.append("  return { " + ", ".join(obj_parts) + " } as any;")

    lines.append("}")
    lines.append("")
    lines.append("// Bridge metadata (structured, non-autonomous stubs)")
    lines.append("export const BRIDGE_CONFIG = " + repr(ir.bridge_config).replace("'", '"') + " as const;")
    if ir.tesla_victory_layer:
        merged = ir.arc_tower_policy | ir.life_ray_protocol | ir.breath_cycle_protocol
        lines.append("export const TESLA_VICTORY_LAYER = " + repr(merged).replace("'", '"') + " as const;")
    if ir.agentora_config.get("enabled"):
        lines.append("export const AGENTORA_CONFIG = " + repr(ir.agentora_config).replace("'", '"') + " as const;")
        lines.append("export const AGENT_DEFINITIONS = " + repr(ir.agent_definitions).replace("'", '"') + " as const;")
    if ir.agentception_config:
        lines.append("export const AGENTCEPTION_CONFIG = " + repr(ir.agentception_config).replace("'", '"') + " as const;")

    return "\n".join(lines) + "\n"
